import React from "react";


export const AppList = [
    { id: 1, name: 'OPDocuments' },
    { id: 2, name: 'OPSheets' },
    { id: 3, name: 'OPBrowser' },
    { id: 4, name: 'OPGame-hub' },
    { id: 5, name: 'OPTinder' },
    { id: 6, name: 'OPGrinder' },
    { id: 7, name: 'OPCalculator' },
    { id: 8, name: 'OPMemos' },
    { id: 9, name: 'OPPhotos' },
    { id: 10, name: 'OPWeather' },
    { id: 11, name: 'OPMaps' },
    { id: 12, name: 'OPContacts' },
    { id: 13, name: 'OPCalendar' },
    { id: 14, name: 'OPMusic' },
    { id: 15, name: 'OPCamera' },
    { id: 16, name: 'OPMail' },
    { id: 17, name: 'OPMessenger' },
    { id: 18, name: 'OPNews' },
    { id: 19, name: 'OPTranslator' },
    { id: 20, name: 'OPNotes' },
    { id: 21, name: 'OPWallet' },
    { id: 22, name: 'OPFitness' },
    { id: 23, name: 'OPRecipes' },
    { id: 24, name: 'OPPodcasts' },
    { id: 25, name: 'OPVideos' },
    { id: 26, name: 'OPShop' },
    { id: 27, name: 'OPTasks' },
    { id: 28, name: 'OPQuotes' },
    { id: 29, name: 'OPGoals' },
    { id: 30, name: 'OPSleep' },
];